spring.application.name=Stock
# URL de la base de donn�es (localhost:3306 est le port par d�faut de MySQL)
# spring.datasource.url=jdbc:mysql://localhost:3306/stock_pro?serverTimezone=UTC&useSSL=false
# spring.datasource.username=root
# spring.datasource.password=

# Hibernate : On utilise 'update' pour ne pas supprimer les donn�es � chaque red�marrage
# spring.jpa.hibernate.ddl-auto=update

# Pour voir les requ�tes SQL dans la console (pratique pour d�bugger)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#spring.datasource.url=jdbc:h2:mem:stockdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Personnaliser les endpoints Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

// HEBERGEMENT SUR RAILWAY
spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:18076/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=oajxSEXsrLkFHGuoozHyaSVfZRqdUucp

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true